language: go

go:
  - 1.4

install:
   - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.17.zip 
   - unzip -q go_appengine_sdk_linux_amd64-1.9.17.zip
   - ./go_appengine/goapp version

script: ./go_appengine/goapp test -v
