language: go

go:
  - 1.4

# we're in $HOME/gopath/src/github.com/tp/fetchall
install:
  - mkdir $HOME/aesdk
  - cd $HOME/aesdk
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.17.zip 
  - unzip -q go_appengine_sdk_linux_amd64-1.9.17.zip
  - cd -
  - $HOME/aesdk/go_appengine/goapp version
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

script:
  - go vet ./...
  - golint ./...
  - $HOME/aesdk/go_appengine/goapp/go_appengine/goapp test -v ./...
