language: go

go:
  - 1.3
  - 1.4
  - tip

install:
   - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.17.zip && unzip -q go_appengine_sdk_linux_amd64-1.9.17.zip

script: ./go_appengine/goapp test -v
